[ADD] New components
Touxooo/archi-arcade-toulouse pull request #7
Opened 2022-03-27 17:40 UTC by JohannSako

Rect component for sprite position and size in spritesheet
Scale component for sprite size augmentation in the window
Sprite2D for sprite filepath assets
SpriteText for sprite text in NCurses
Vector3D update to set values in constructor

2022-03-29 13:00 UTC, iDommel commented on include/ecs/components/Rect.hpp
> +    #include "ecs/components/IComponent.hpp"
Ces includes ne sont pas nécessaires si tu fais ton makefile / Cmake correctement, juste IComponent.hpp suffit

2022-03-29 13:02 UTC, iDommel commented on include/ecs/components/Rect.hpp
> +
Typiquement sur des classes simples comme ça qui ont de grande chances d'avoir été appelées pareil dans d'autres libs faut utiliser les namespace

2022-03-29 13:04 UTC, iDommel requested changes
Petites retouches à faire:

- Ajouter le namespace arcade
- Enlever les paths relatifs sur les include

2022-03-30 09:19 UTC, Varriss commented on include/ecs/components/Scale.hpp
> +            double _width;
"_widthMod" plus clair ?

2022-03-30 09:21 UTC, Varriss commented on include/ecs/components/Scale.hpp
> +            double _width;
et le scale peut aussi impacter la profondeur, donc faut rajouter le Z

2022-03-30 13:20 UTC, closed without merging

2022-03-30 13:20 UTC, JohannSako commented
Modification of the pull request branch