[ADD] Sound component
Touxooo/archi-arcade-toulouse pull request #9
Opened 2022-03-29 13:21 UTC by martindlh1

Ajout d'un composant son avec un filepath et un booléen

2022-03-29 13:25 UTC, iDommel approved these changes

2022-03-29 15:03 UTC, martindlh1 reviewed
deux booléen _start & _stop me paraisse plus pratique poour gerer music et son avce le meme composant sur toutes les libs

2022-03-29 15:17 UTC, iDommel approved these changes

2022-03-30 08:17 UTC, iDommel requested changes
Manque namespace arcade

2022-03-30 22:23 UTC, iDommel commented on include/components/Sound.hpp
> +class Sound : public IComponent {
Attention Il manque toujours le namespace

2022-03-30 22:23 UTC, iDommel reviewed
Ok pour les shared ptr, attention au namespace sur le component

2022-04-03 18:07 UTC, martindlh1 reviewed
Modifcation du component Sound reflechis avec Johan
Ajout d'un composant Rotation qui contient un float _angle

2022-04-04 08:58 UTC, merged